url: https://api.spoonacular.com/recipes/findByIngredients

api_key: Your_api_key_here
ingredient:
  -orange
  -avocado
  -cucumber
  -pepper
  -pumpkin
  -carrot
  -garlic
  -radish
  -potato
  -apple
  -plum